### ISSUE TITLE
0.7.8 Generate 0bytes file

### ISSUE THREAD

**Issue by ensi-labs** [yogthos/json-to-pdf#14]
The version 0.7.8 generates files with 0 bytes size.

**Comment by yogthos** [comment]
Going to have to investigate, looks like clj-pdf might've changed sufficiently to break the API.

**Comment by yogthos** [comment]
Looks like the issue happens when using an output stream.

**Comment by yogthos** [comment]
Looks like the issue is specifically with the `"pages":true` option.

**Comment by yogthos** [comment]
ok I just pushed out version `0.7.9` that should fix the issue
