### ISSUE TITLE
Cannot get gradle or maven to run after installing

### ISSUE THREAD

**Issue by tomdoe420** [yogthos/json-to-pdf#15]
For Maven
![enviornment varibles](https://user-images.githubusercontent.com/32225549/40558876-bc7bae20-6022-11e8-8209-eab49ed63ce4.JPG)
![ev](https://user-images.githubusercontent.com/32225549/40560250-6abce676-6027-11e8-9217-4d9e076c22e2.JPG)

![maven powershell](https://user-images.githubusercontent.com/32225549/40558046-1e197d7c-6020-11e8-9edc-9c0d240d7621.JPG)

For Gradle
This is weird now I'm getting this after installing Maven
`PS C:\Gradle> gradle -v

ERROR: JAVA_HOME is set to an invalid directory: C:\maven

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
PS C:\Gradle> java -version
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)`

I also ran
`iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
scoop install gradle`
this in cmd not powershell
`@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"`
But decided not to install it as I realized I just needed to run for gradle to be installed
`scoop install gradle`

I don't know if this is what I need to do to run gradle, but I ran
`❯ mkdir basic-demo
❯ cd basic-demo
❯ gradle init
Starting a Gradle Daemon (subsequent builds will be faster)

BUILD SUCCESSFUL in 3s
2 actionable tasks: 2 executed`
according to this [tutorial](https://guides.gradle.org/creating-new-gradle-builds/)

And that's where I got lost and confused and decided to try Maven instead. I think I would rather use Maven since it looks simpler, but after installing it both are not recognizing my Java directory. What do I do?

**Comment by yogthos** [comment]
The issue appears to be with your environment setup, and not any library specific functionality. Unfortunately, I don't use gradle myself so I can't really help troubleshoot this.
