### ISSUE TITLE
Is it possible to use unicode fonts?

### ISSUE THREAD

**Issue by mouserd** [yogthos/json-to-pdf#18]
Hi,

I'm wanting to display unicode currency symbols in my pdfs and I haven't been able to work out how to do it.  Is this possible?

Thanks!

**Comment by yogthos** [comment]
Custom font encoding is supported by the underlying library, see the docs [here](https://github.com/clj-pdf/clj-pdf#using-custom-ttf-fonts). That should theoretically work via the wrapper as well:

```json
[{"font": {"encoding": "unicode",
               "ttf-name": "fonts/arialuni.ttf"}},
  ["phrase" "тест 123"]]
```

I haven't tested this though.

**Comment by mouserd** [comment]
Thanks for the quick reply... I think it looks like it will work but I'm just a little confused where that "font" block should be placed.  Is that part of the main document "metadata"?

**Comment by yogthos** [comment]
Right, that would be the document level metadata.

**Comment by mouserd** [comment]
OK I got it working, it turned out that the "encoding": "unicode" was causing a problem with my custom ttf font.  Thanks for your help!

**Comment by yogthos** [comment]
Fantastic, glad to hear everything's working.
