### ISSUE TITLE
Question : background-color on header of table affecting the whole table.

### ISSUE THREAD

**Issue by jarey** [yogthos/json-to-pdf#20]
Hello,

Thanks again for this awesome library.

I'm experiencing a behaviour that i would like to confirm if its expected.

I'm applying the background-color property to a table header, and the color is affecting all the rows of the table.

The json i'm using is the following:

`[
   {
      "top-margin":100,
      "bottom-margin":25,
      "left-margin":58,
      "right-margin":44,
      "size":"a4"
   },
   [
      "paragraph",
      [
         "chunk",
         "Content before table."
      ]
   ],
   [
      "paragraph",
      [
         "chunk",
         "Some other content."
      ]
   ],
   [
      "paragraph",
      [
         "chunk",
         "Content before table."
      ]
   ],
   [
      "table",
      {
         "header":[
            "Row 1",
            "Row 2",
            "Row 3"
         ],
         "width":50,
         "border":false,
         "cell-border":false,
         "background-color":[
            100,
            50,
            100
         ]
      },
      [
         [
            "cell",
            {
               "colspan":2
            },
            "Foo"
         ],
         "Bar"
      ],
      [
         "foo1",
         "bar1",
         "baz1"
      ],
      [
         "foo2",
         "bar2",
         "baz2"
      ]
   ]
]`

Wich produces the following pdf:

[https://drive.google.com/open?id=1HmBQBF1Os0rijAlDqPWct7mDrYHQ9gD8](https://drive.google.com/open?id=1HmBQBF1Os0rijAlDqPWct7mDrYHQ9gD8)

Is it expeted behaviour, or the color should only be applied to the header (only the first row)?.

Thanks in advance.

**Comment by jarey** [comment]
Just realized double-checking the documentation that the metadata affects the table. Totally incorrect usage from me, in the use-case i was pretending.

All behaves as expected.

Sorry and thanks again.

**Comment by yogthos** [comment]
No worries, and glad to hear the library's been useful. :)
