### ISSUE TITLE
Possibility to use custom font-family.

### ISSUE THREAD

**Issue by jarey** [yogthos/json-to-pdf#21]
Hello @yogthos, and once again thanks for this awesome library.

I was wondering if it would be possible to add support to specifying custom font-family in order to be used by the library.

The documentation illustrates that only certain font families are supported; ¿would it be possible to add support?

We would happily contribute if you can give a piece of advice on how to approach the change if needed.

Thanks in advance.

Kind regards.

**Comment by jarey** [comment]
As seen in clj-pdf, could be possible to expose custom font-family configuration attributes in json-to-pdf?

https://github.com/clj-pdf/clj-pdf#using-custom-ttf-fonts

Thanks again.

**Comment by jarey** [comment]
Double-checked the documentation on clj-pdf and tested if the json-to-pdf java wrapper executed OK with the ttf-name, undocumented for the wrapper.

Result was ok, so support is already provided.

Closing this issue, thanks one again.

@yogthos, if you want a pullt request with a documentation update for this part, would gladly elaborate one for the readme.md; just let me know.

**Comment by yogthos** [comment]
@jarey a PR for updated docs would be greatly appreciated :)
