### ISSUE TITLE
RFC json-to-pdf

### ISSUE THREAD

**Issue by ghost** [yogthos/json-to-pdf#22]
Hi everyone.

I wonder if there is any technical specification like RFC for json-to-pdf. *Is there any technical specification like RFC for json-to-pdf?*

**Comment by yogthos** [comment]
Hi, there isn't a technical specification for the project aside from the docs in the readme.

**Comment by ghost** [comment]
Hi yogthos.

> Hi, there isn't a technical specification for the project aside from the docs in the readme.

thank you for feedback.  I'm closing this issue, all my questions have been answered.
