### ISSUE TITLE
Unable to use pagebreak tag from clj-pdf

### ISSUE THREAD

**Issue by jakinho** [yogthos/json-to-pdf#6]
Hi!

I know that pagebreak tag is not in your documentation, but I tried to use it because this simply 'translate' json to your clj-pdf format. But when I try to write to pdf a json that includes ["pagebreak"], it throws the following exception (with stacktrace):

Caused by: java.lang.Exception: invalid tag: :pagebreak in element: ["pagebreak"]
	at clj_pdf.core$make_section.invoke(core.clj:665) [json-to-pdf-0.6.9.jar:]
	at clj_pdf.core$append_to_doc.invoke(core.clj:681) [json-to-pdf-0.6.9.jar:]
	at clj_pdf.core$add_item.invoke(core.clj:813) [json-to-pdf-0.6.9.jar:]
	at clj_pdf.core$seq_to_doc.invoke(core.clj:853) [json-to-pdf-0.6.9.jar:]
	at clj_pdf.core$pdf.invoke(core.clj:874) [json-to-pdf-0.6.9.jar:]
	at json_to_pdf.core$_writeToFile.invoke(core.clj:12) [json-to-pdf-0.6.9.jar:]

I tried to follow this on clf-pdf core but I know nothing about clojure. It seems to recognize the :pagebreak tag but then sends the item again to make-section and is not one of the expected values. Could you tell me if I'm doing something wrong or if there is a way of achieve this? Is this tag not going to be available ever in json-to-pdf?

Thanks!

**Comment by yogthos** [comment]
It's not currently supported, I think the issue is with how the tag ends up being deserialized from JSON so I'd have to treat it as a special case.

**Comment by jarey** [comment]
Hi!

Any plans on having this working soon?
I need it for a project too and would be glad to have it working using your library instead of using a workaround or second library in order to achieve the pagebreak.

Thanks in advance.

**Comment by yogthos** [comment]
I just pushed out `json-to-pdf "0.7.1"` with the fix, let me know if it works for you.

**Comment by jakinho** [comment]
Hi, it's working perfectly with this new version.

Thanks!!

**Comment by jarey** [comment]
Hi!

It's woking like a charm for me too. Thank you very much!

PS. Do you have any donation link to buy you a beer? Regards.

**Comment by yogthos** [comment]
glad to hear it, and don't have a donation link but thanks for the thought :)
