### ISSUE TITLE
java.lang.ClassCastException: java.io.ByteArrayInputStream cannot be cast to java.io.Reader

### ISSUE THREAD

**Issue by andrewslack** [yogthos/json-to-pdf#7]
code:

String doc = "[{}, [\"paragraph\", \"hello world\"]]";
InputStream inputStream = new ByteArrayInputStream(doc.getBytes());
OutputStream outputStream = new ByteArrayOutputStream();
JsonPDF.writeToStream(inputStream, outputStream);

Results in:

java.lang.ClassCastException: java.io.ByteArrayInputStream cannot be cast to java.io.Reader
	at cheshire.core$parse_stream.invoke(core.clj:190)
	at cheshire.core$parse_stream.invoke(core.clj:186)
	at json_to_pdf.core$parse.invoke(core.clj:16)
	at json_to_pdf.core$_writeToStream.invoke(core.clj:22)
	at org.yogthos.JsonPDF.writeToStream(Unknown Source)

Given that my hands are tied in that I can only provide an Inputstream why is the impl trying to convert to a Reader and more importantly what can I do to convince it otherwise?

Thanks.

**Comment by yogthos** [comment]
looks like this was a regression from the last update, just pushed out `0.7.2` with a fix

**Comment by andrewslack** [comment]
Thanks -- that did it.
