### ISSUE TITLE
java.lang.UnsupportedOperationException: nth not supported on this type: PersistentHashMap

### ISSUE THREAD

**Issue by andrewslack** [yogthos/json-to-pdf#8]
String doc = "{" +
                "    \"right-margin\": 10," +
                "    \"subject\": \"hello world\"," +
                "    \"creator\": \"Jane Doe\"," +
                "    \"doc-header\": [" +
                "      \"inspired by\"," +
                "      \"William Shakespeare\"" +
                "    ]," +
                "    \"bottom-margin\": 25," +
                "    \"pages\": true," +
                "    \"author\": \"someone\"," +
                "    \"header\": \"Page header text appears on each page\"," +
                "    \"left-margin\": 10," +
                "    \"title\": \"Test doc\"," +
                "    \"size\": \"a4\"," +
                "    \"letterhead\": [" +
                "      \"A simple Letter head\"" +
                "    ],\n" +
                "    \"orientation\": \"landscape\"," +
                "    \"font\": {" +
                "      \"size\": 11" +
                "    },\n" +
                "    \"footer\": \"Page footer text appears on each page (includes page number)\"," +
                "    \"top-margin\": 20" +
                "  }";
    
        InputStream inputStream = new ByteArrayInputStream(doc.getBytes());
        OutputStream outputStream = new ByteArrayOutputStream();
        JsonPDF.writeToStream(inputStream, outputStream);

Results in:

java.lang.UnsupportedOperationException: nth not supported on this type: PersistentHashMap
	at clojure.lang.RT.nthFrom(RT.java:857)
	at clojure.lang.RT.nth(RT.java:807)
	at clj_pdf.core$write_doc.invoke(core.clj:879)
	at clj_pdf.core$pdf.invoke(core.clj:932)
	at json_to_pdf.core$parse.invoke(core.clj:16)
	at json_to_pdf.core$_writeToStream.invoke(core.clj:22)
	at org.yogthos.JsonPDF.writeToStream(Unknown Source)

**Comment by yogthos** [comment]
That JSON is not following the document syntax, please read the documentation to see how to construct a proper document.

**Comment by andrewslack** [comment]
ack, sorry.
